### PR TITLE
Quote Functionality

### PR DESCRIPTION
**Pull request by Palehors68**
Added Quote functionality. Mods can add a quote (or remove all quotes).
Everyone can request a quote.

Commands:
!addquote This is the quote.
!removeallquotes
!quote

Quotes are stored in quotes.txt in the default directory.

### CODE REVIEW

**Comment by mikesmiffy128** [comment]
So this is just randomised text? Shouldn't that already be possible? If not it would make sense to add something more general instead.

**Comment by Palehors68** [comment]
Not sure what you mean by randomized text. The idea is that the streamer says something funny or ridiculous or whatever, and the mods have the ability to capture the funny quote. All the quotes are then stored in a master list, and when someone requests a !quote, botnak picks a random one from that list and displays it.

**Comment by mikesmiffy128** [comment]
You just explained what I meant by randomised text. Generally the funny things get made into sounds anyway. Text quotes would just flood the chat and wouldn't capture much of the contextual hilarity. I don't know what Gochai thinks though.

**Comment by Palehors68** [comment]
Oh gotcha. I guess if the chat was being flooded, you could just allow subs to request a quote.

**Comment by mikesmiffy128** [comment]
I just took a look at the patch and it looks like you've actually made it a mod command anyway. I tale it this is a mistake?

**Comment by Palehors68** [comment]
Ahh, yes, the !quote command should have been PERMISSION_ALL.

**Pull request closed without merging**
