### PR TITLE
Refactoring galore! (Also, new !volume command)

### PR DESCRIPTION
**Pull request by Chrisazy**
So I refactored everything. Luckily, merge strategies will probably make it so that you won't have to manually merge in any existing changes you haven't pushed yet. There were a couple of reflection/class loader issues with the Look and Feel. I fixed all of the ones for new botnak installations, for sure. I'm like 99% sure that I fixed it for existing ones, but there's a chance that you'll have to delete lafa.txt or manually change the value, since the class location was being hardcoded and also saved to a file. If you have any troubles or doubts when merging your changes, make an issue and @chrisazy, I'll get it via email

### CODE REVIEW

**Comment by Gocnak** [comment]
Next time try to make each change its own commit; makes it easier to see every change.

For example in this pull, your !volume code was buried under the refactoring. Not anything other than a nuisance.

**Comment by Gocnak** [comment]
But great work, I'll be committing the new main GUI soon to merge.

**Comment by Chrisazy** [comment]
Yeah, I commited along the way like a good boy, but then I broke my head, so I had to do it manually, thus the one huge commit :(

**Comment by Chrisazy** [comment]
Moving my changes to different branches. Also, going to wait for this huge GUI change and refactor again when @Gocnak takes a break ;)

**Pull request closed without merging**
